<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoice {{ $invoice->stripe_invoice_id ?? '#'.$invoice->id }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #1a1a1a; margin: 2rem; }
        .header { display: flex; justify-content: space-between; margin-bottom: 2rem; }
        .brand { font-size: 1.4rem; font-weight: 700; color: #0f172a; }
        .meta { text-align: right; font-size: 11px; color: #64748b; }
        table { width: 100%; border-collapse: collapse; margin-top: 1.5rem; }
        th { text-align: left; border-bottom: 2px solid #e2e8f0; padding: 0.5rem 0; font-size: 11px; text-transform: uppercase; color: #64748b; }
        td { padding: 0.6rem 0; border-bottom: 1px solid #f1f5f9; }
        .total { font-weight: 700; font-size: 1.1rem; }
        .footer { margin-top: 3rem; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 1rem; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 10px; font-weight: 600; }
        .badge-paid { background: #dcfce7; color: #166534; }
        .badge-open { background: #fef3c7; color: #92400e; }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand">{{ $appName }}</div>
        <div class="meta">
            <div><strong>Invoice</strong></div>
            <div>{{ $invoice->stripe_invoice_id ?? 'INV-'.str_pad($invoice->id, 6, '0', STR_PAD_LEFT) }}</div>
            <div>{{ $invoice->paid_at?->format('F j, Y') ?? $invoice->created_at?->format('F j, Y') ?? '—' }}</div>
        </div>
    </div>

    @if($customer)
    <div style="margin-bottom: 1.5rem;">
        <strong>Bill to:</strong><br>
        {{ $customer->name ?? '—' }}<br>
        {{ $customer->email ?? '—' }}
    </div>
    @endif

    <table>
        <thead>
            <tr><th>Description</th><th style="text-align:right">Amount</th><th>Status</th></tr>
        </thead>
        <tbody>
            <tr>
                <td>Invoice {{ $invoice->stripe_invoice_id ?? '#'.$invoice->id }}</td>
                <td style="text-align:right" class="total">${{ number_format(($invoice->amount_due_cents ?? 0) / 100, 2) }} {{ $invoice->currency ?? 'USD' }}</td>
                <td><span class="badge badge-{{ $invoice->status === 'paid' ? 'paid' : 'open' }}">{{ ucfirst($invoice->status ?? 'unknown') }}</span></td>
            </tr>
        </tbody>
    </table>

    @if($payments && $payments->count() > 0)
    <h3 style="margin-top: 2rem; font-size: 12px; color: #475569;">Payments</h3>
    <table>
        <thead><tr><th>Date</th><th style="text-align:right">Amount</th><th>Status</th><th>Reference</th></tr></thead>
        <tbody>
        @foreach($payments as $pay)
            <tr>
                <td>{{ $pay->paid_at?->format('Y-m-d') ?? $pay->created_at?->format('Y-m-d') ?? '—' }}</td>
                <td style="text-align:right">${{ number_format(($pay->amount_cents ?? 0) / 100, 2) }} {{ $pay->currency ?? 'USD' }}</td>
                <td>{{ $pay->status ?? '—' }}</td>
                <td style="font-size:10px;color:#64748b">{{ $pay->stripe_payment_intent_id ?? '—' }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

    <div class="footer">
        Generated by {{ $appName }} · {{ now()->format('F j, Y g:i A') }} · This is not a tax invoice.
    </div>
</body>
</html>

