FROM php:8.3-cli

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    git unzip zip curl libzip-dev libpq-dev libonig-dev \
 && docker-php-ext-install pdo pdo_mysql pdo_pgsql mbstring zip \
 && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

WORKDIR /app
